--- 
- name: Download k3s installer
  get_url:
    url: "https://get.k3s.io"
    dest: /tmp/install_k3s.sh
    mode: '0755'

- name: Join to master
  shell: /tmp/install_k3s.sh - server --server {{ hostvars['master']['master_node_ip'] }}
  environment:
    - K3S_KUBECONFIG_MODE: "{{ K3S_KUBECONFIG_MODE }}"
    - INSTALL_K3S_VERSION: "{{ INSTALL_K3S_VERSION }}"
    - INSTALL_K3S_EXEC: "{{ INSTALL_K3S_EXEC }}"
    - K3S_TOKEN: "{{ hostvars['master']['k3s_token'] }}"

- name: debug var
  include_role:
    name: master
    
- name: token
  debug:
    var: hostvars['master']['k3s_token']

- name: debug_ip
  debug:
    var: hostvars['master']['master_node_ip']